import Head from 'next/head'
import Navigation from '../components/Navigation'
import Patients from '../components/Patients'

export default function Home() {
  return (
    <>
      <Head>
        <title>Himilo Doctor Booking</title>
        <meta name='description' content='Generated by Himilo Doctor Booking' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <div className='container'>
        <Patients />
      </div>
    </>
  )
}
